### ISSUE TITLE
Remap Cmd + W

### ISSUE THREAD

**Issue by ALEUT** [dezhaoli/MicrosoftRemoteDesktop-Setting#1]
Actually Cmd + W can be remapped also, it's enough to create such a record in system settings:
<img width="720" alt="image" src="https://github.com/dezhaoli/MicrosoftRemoteDesktop-Setting/assets/4101909/559d1728-6824-4802-b10e-7a1dd36d62c9">

After that Close action will be changed to this new combination and Cmd + W will work fine.

Thank you for your work!

**Comment by ALEUT** [comment]
And change W to upper case like:
```
<transform>
  <from command="1" key="W" />
  <to control="1" key="W" />
</transform>
```

**Comment by dezhaoli** [comment]
@ALEUT  Thank you  for your solution, Cmd + W is work!
